# Generated by Django 4.1.1 on 2022-10-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_otp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otp',
            options={'verbose_name_plural': 'کدتاید'},
        ),
        migrations.AddField(
            model_name='otp',
            name='token',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='code',
            field=models.SmallIntegerField(verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='number',
            field=models.CharField(max_length=11, verbose_name='شماره'),
        ),
    ]
