# Generated by Django 4.1.1 on 2023-05-21 12:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='times',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='times'),
            preserve_default=False,
        ),
    ]
